name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Match your venv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to DigitalOcean Staging
        env:
          DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
          DO_HOST: 24.144.88.28
        run: |
          echo "$DO_SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key root@$DO_HOST << 'EOF'
            cd /var/www/staging_ai_dungeon_master
            git pull origin staging
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f "gunicorn.*8001"
            gunicorn --workers 3 --bind 127.0.0.1:8001 app:app &
          EOF
